---
- name: System configuration for Servy
  hosts: all
  become: true

  roles:
    - role: system

    - role: ssh

    # - role: drives

    # - role: tigattack.mergerfs

    # - role: geerlingguy.pip

    # - role: geerlingguy.docker

    # - role: docker
