---
- name: System configuration for Servy
  hosts: all
  become: true

  roles:
    - {role: 'system', tags: 'system'}
    - {role: 'filesystem', tags: 'filesystem'}
    - {role: 'ssh', tags: 'ssh'}
    - {role: 'geerlingguy.pip', tags: 'geerlingguy.pip'}
    - {role: 'geerlingguy.docker', tags: 'geerlingguy.docker'}
    - {role: 'docker', tags: 'docker'}
