- name: Configure sshd
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" }
  notify: "restart ssh daemon"

- name: Fetch ssh keys from github
  ansible.builtin.uri:
    url: "https://github.com/Quadrubo.keys"
    return_content: true
  register: github_keys

- name: Ensure ssh keys from github are copied
  ansible.posix.authorized_key:
    user: "julian"
    state: present
    key: "{{ item }}"
  loop: "{{ github_keys.content.splitlines() }}"
