- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install essential packages
  ansible.builtin.package:
    name: "{{ system_packages }}"
    state: latest
    only_upgrade: true
