- name: Ensure all necessary groups are created
  ansible.builtin.group:
    name: "{{ item }}"
  loop: "{{ system_groups | union(system_users | map(attribute='groups') | flatten) }}"

- name: Ensure non-root users are created
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
    groups: "{{ item.groups }}"
    append: true
    shell: "{{ item.shell }}"
    update_password: on_create
  loop: "{{ system_users }}"
  when: item.create | default(true) | bool

- name: Enable passwordless sudo for users
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^%whell"
    line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  loop: "{{ system_users }}"
  when: item.passwordless_sudo | default(false) | bool
