- name: Ensure all necessary groups are created
  ansible.builtin.group:
    name: "{{ item }}"
  loop:
    - docker
    - samba
    - "{{ system_username }}"

- name: Ensure the non-root user is created
  ansible.builtin.user:
    name: "{{ system_username }}"
    password: "{{ system_password | password_hash('sha512') }}"
    groups:
      - sudo
      - docker
      - users
    append: true
    shell: "{{ system_shell }}"
    update_password: on_create

- name: Enable passwordless sudo for "{{ system_username }}"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^%whell"
    line: "{{ system_username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Suppress login message (hushlogin)
  ansible.builtin.file:
    path: "/home/{{ system_username }}/.hushlogin"
    mode: "0644"
    owner: "{{ system_username }}"
    group: "{{ system_username }}"
    modification_time: preserve
    access_time: preserve
    state: touch
