- name: Copy compose files
  ansible.builtin.copy:
    src: data/containers/
    dest: /srv/containers
    mode: "0644"
    owner: "{{ system_username }}"
    group: "{{ system_username }}"

- name: Test docker-compose
  community.docker.docker_compose_v2:
    project_src: "/srv/containers/{{ item }}"
    state: present
  loop: "{{ docker_containers }}"
